CSS = r"""
.qh{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.qh h1{margin:0!important}.sub,.meta,.help{color:#667085;font-size:10px}.kpis,.grid{display:grid;gap:10px}.kpis{grid-template-columns:repeat(4,1fr);margin:14px 0}.grid{grid-template-columns:1fr 1fr}.card,.kpi{border:1px solid #e4e7ec;border-radius:10px;background:#fff;padding:14px}.kpi b{display:block;font-size:22px}.tabs{display:flex;gap:4px;flex-wrap:wrap;padding:4px;background:#f2f4f7;border-radius:9px;margin-bottom:12px}.tab{border:0;border-radius:7px;padding:8px 10px;background:transparent;font:inherit;font-size:10px;font-weight:800;cursor:pointer}.tab.on{background:#fff}.panel{display:none}.panel.on{display:block}.row{display:flex;justify-content:space-between;gap:9px;padding:9px 0;border-top:1px solid #eaecf0}.row:first-child{border-top:0}.main{flex:1;min-width:0}.title{font-size:11px;font-weight:850;color:#344054}.badge{display:inline-flex;padding:4px 7px;border-radius:999px;background:#f2f4f7;color:#475467;font-size:9px;font-weight:800}.fail{background:#fee4e2;color:#b42318}.pass{background:#dcfae6;color:#067647}.block{background:#fef0c7;color:#b54708}.info{background:#eaf2ff;color:#175cd3}.form{display:grid;gap:8px}.form label{font-size:10px;font-weight:800;color:#344054}.form input,.form select,.form textarea{width:100%;border:1px solid #d0d5dd;border-radius:8px;font:inherit;font-size:10px}.form input,.form select{height:36px;padding:0 8px}.form textarea{min-height:78px;padding:8px}.inline{display:flex;gap:7px;align-items:end}.inline>*{flex:1}.inline button{flex:0 0 auto}.checks{display:grid;gap:5px}.check{display:flex!important;gap:7px;align-items:flex-start}.check input{width:15px!important;height:15px!important}.criteria{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin:8px 0}.criterion{padding:8px;border-radius:8px;background:#f9fafb;font-size:9px}.criterion.y{background:#ecfdf3}.criterion.n{background:#fef3f2}.table{width:100%;border-collapse:collapse;font-size:9px}.table th,.table td{padding:7px;border-top:1px solid #eaecf0;text-align:left;vertical-align:top}.table th{background:#f9fafb;color:#667085}.scroll{overflow:auto}.analysis{padding:10px;border:1px solid #d1e0ff;border-radius:8px;background:#f5f8ff;font-size:10px;line-height:1.45}.stack{display:grid;gap:10px}@media(max-width:950px){.grid{grid-template-columns:1fr}.criteria{grid-template-columns:1fr 1fr}.kpis{grid-template-columns:1fr 1fr}}@media(max-width:600px){.inline,.row{flex-direction:column}.kpis,.criteria{grid-template-columns:1fr}}
"""

JS = r"""<script>(function(){function show(k){const t=document.querySelector('[data-qtab="'+k+'"]'),p=document.querySelector('[data-qpanel="'+k+'"]');if(!t||!p)return;document.querySelectorAll('[data-qtab]').forEach(x=>x.classList.remove('on'));document.querySelectorAll('[data-qpanel]').forEach(x=>x.classList.remove('on'));t.classList.add('on');p.classList.add('on')}document.addEventListener('click',e=>{const t=e.target.closest('[data-qtab]');if(!t)return;show(t.dataset.qtab);history.replaceState(null,'','#'+t.dataset.qtab)});show(location.hash.slice(1)||document.body.dataset.qaTab||'work')})();</script>"""

PAGE = r"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QA Workspace</title><style>{{ css|safe }}</style></head><body data-qa-tab="{{ active_tab }}"><main class="th-page">
<div class="qh"><div><h1>QA Workspace</h1><div class="sub">Tester workflow: what to test, what failed, what is blocked, what needs retest, and what is ready for release review.</div></div><a class="prd-btn" href="{{ url_for('test_plans') }}">Test Plans</a></div>
<div class="kpis"><div class="kpi"><b>{{ work.testing|length }}</b><span class="meta">Needs testing</span></div><div class="kpi"><b>{{ work.retest|length }}</b><span class="meta">Needs retest</span></div><div class="kpi"><b>{{ work.blocked|length }}</b><span class="meta">Blocked</span></div><div class="kpi"><b>{{ work.auto_failed|length }}</b><span class="meta">Failed automation</span></div></div>
<div class="tabs">{% for key,label in [('work','My Testing'),('gaps','Coverage Gaps'),('release','Release Readiness'),('risk','Risk'),('impact','Smart Scope / AI'),('explore','Exploratory'),('auto','Automation Health')] %}<button class="tab {% if loop.first %}on{% endif %}" data-qtab="{{ key }}">{{ label }}</button>{% endfor %}</div>

<section class="panel on" data-qpanel="work"><div class="grid">
<div class="card"><h2>Needs Testing</h2>{% for r in work.testing %}<div class="row"><div class="main"><a class="title" href="{{ url_for('test_case_details',case_key=r.case.case_key) }}">{{ r.case.case_key }} — {{ r.case.title }}</a><div class="meta">{{ r.case.feature_name }} · {{ r.case.priority }} · {{ r.case.type }}</div></div><span class="badge info">Ready</span></div>{% else %}<div class="help">No first executions waiting.</div>{% endfor %}</div>
<div class="card"><h2>Needs Retest</h2>{% for r in work.retest %}<div class="row"><div class="main"><a class="title" href="{{ url_for('test_case_details',case_key=r.case.case_key) }}">{{ r.case.case_key }} — {{ r.case.title }}</a><div class="meta">Failed {{ r.result.executed_at.strftime('%d %b %H:%M') }}{% if r.defects %} · {{ r.defects|join(', ') }}{% endif %}{% if r.retest %} · {{ r.state }}{% endif %}</div></div><div>{% if r.retest and r.retest.retest_run_id %}<a class="prd-btn" href="{{ url_for('test_run_details',run_id=r.retest.retest_run_id) }}">Open retest</a>{% elif r.retest %}<form method="post" action="{{ url_for('qa_create_retest',result_id=r.result.id) }}"><button class="prd-btn prd-btn-primary">Create retest</button></form>{% else %}<form class="inline" method="post" action="{{ url_for('qa_mark_retest',result_id=r.result.id) }}"><input name="defect_key" value="{{ r.defects[0] if r.defects else '' }}" placeholder="BUG-123"><button class="prd-btn">Ready</button></form>{% endif %}</div></div>{% else %}<div class="help">No failed cases need retesting.</div>{% endfor %}</div>
<div class="card"><h2>Blocked</h2>{% for r in work.blocked %}<div class="row"><div class="main"><a class="title" href="{{ url_for('test_case_details',case_key=r.case.case_key) }}">{{ r.case.case_key }} — {{ r.case.title }}</a><div class="meta">{{ r.context.blocked_reason if r.context else 'Reason not recorded' }}</div></div><form class="form" method="post" action="{{ url_for('qa_result_context',result_id=r.result.id) }}"><select name="blocked_reason"><option value="">Reason…</option>{% for v in block_reasons %}<option {% if r.context and r.context.blocked_reason==v %}selected{% endif %}>{{ v }}</option>{% endfor %}</select><input name="tester_notes" value="{{ r.context.tester_notes if r.context else '' }}" placeholder="Tester note"><button class="prd-btn">Save</button></form></div>{% else %}<div class="help">No blocked latest results.</div>{% endfor %}</div>
<div class="card"><h2>Failed Automation</h2>{% for r in work.auto_failed %}<div class="row"><div class="main"><a class="title" href="{{ url_for('test_run_details',run_id=r.result.test_run_id) }}">{{ r.case.case_key }} — {{ r.case.title }}</a><div class="meta">{{ (r.result.error_message or r.result.notes or 'No error recorded')[:160] }}</div></div><span class="badge fail">Failed</span></div>{% else %}<div class="help">No automated latest failures.</div>{% endfor %}</div>
</div></section>

<section class="panel" data-qpanel="gaps"><div class="grid">
<div class="card"><h2>Planned but not created</h2>{% for r in gaps.pending %}<div class="row"><div><a class="title" href="{{ url_for('test_plan_details',plan_id=r.plan.id) }}">{{ r.plan.name }}</a><div class="meta">{{ r.item.feature_snapshot }} · {{ r.item.title_snapshot }}</div></div><span class="badge block">Pending</span></div>{% else %}<div class="help">No pending plan coverage.</div>{% endfor %}</div>
<div class="card"><h2>Unmapped Jira scope</h2>{% for r in gaps.jira %}<div class="row"><div><a class="title" href="{{ url_for('test_plan_details',plan_id=r.plan.id) }}">{{ r.jira_key }}</a><div class="meta">{{ r.plan.name }}</div></div><span class="badge fail">No coverage</span></div>{% else %}<div class="help">No unmapped Jira scope.</div>{% endfor %}</div>
<div class="card"><h2>Never executed</h2>{% for c in gaps.never %}<div class="row"><a class="title" href="{{ url_for('test_case_details',case_key=c.case_key) }}">{{ c.case_key }} — {{ c.title }}</a></div>{% else %}<div class="help">All Ready cases have evidence.</div>{% endfor %}</div>
<div class="card"><h2>No suite classification</h2>{% for c in gaps.unclassified %}<div class="row"><a class="title" href="{{ url_for('test_case_details',case_key=c.case_key) }}">{{ c.case_key }} — {{ c.title }}</a></div>{% else %}<div class="help">All Ready cases are classified.</div>{% endfor %}</div>
</div></section>

<section class="panel" data-qpanel="release"><div class="stack">{% for r in readiness %}<div class="card"><div class="row"><div><h2>{{ r.release.version }}</h2><div class="meta">{{ r.executed }}/{{ r.total }} executed · {{ r.passed }} passed · {{ r.failed }} failed · {{ r.blocked }} blocked</div></div><span class="badge info">{{ r.decision.decision if r.decision else 'Not Assessed' }}</span></div><div class="criteria">{% for c in r.criteria %}<div class="criterion {% if c.state==true %}y{% elif c.state==false %}n{% endif %}"><b>{% if c.state==true %}✓{% elif c.state==false %}✕{% else %}—{% endif %} {{ c.label }}</b><br>{{ c.detail }}</div>{% endfor %}</div><form class="form" method="post" action="{{ url_for('qa_release_decision',release_id=r.release.id) }}"><div class="inline"><label>Human QA decision<select name="decision">{% for v in release_decisions %}<option {% if r.decision and r.decision.decision==v %}selected{% endif %}>{{ v }}</option>{% endfor %}</select></label><label>Comment<input name="comment" value="{{ r.decision.comment if r.decision else '' }}"></label><button class="prd-btn prd-btn-primary">Save</button></div></form></div>{% else %}<div class="card help">No releases yet.</div>{% endfor %}</div></section>

<section class="panel" data-qpanel="risk"><div class="grid"><div class="card"><h2>Assess risk</h2><form class="form" method="post" action="{{ url_for('qa_risk') }}"><label>Test Case<select name="case_id" required><option value="">Select…</option>{% for c in cases %}<option value="{{ c.id }}">{{ c.case_key }} — {{ c.title }}</option>{% endfor %}</select></label>{% for field,label in risk_fields %}<label>{{ label }}<select name="{{ field }}">{% for v in risk_levels %}<option {% if v=='Medium' %}selected{% endif %}>{{ v }}</option>{% endfor %}</select></label>{% endfor %}<label>Notes<textarea name="notes"></textarea></label><button class="prd-btn prd-btn-primary">Save assessment</button></form></div><div class="card"><h2>Risk priority</h2><div class="scroll"><table class="table"><tr><th>Case</th><th>Risk</th><th>Score</th><th>Assessment</th></tr>{% for r in risks %}<tr><td><a href="{{ url_for('test_case_details',case_key=r.case.case_key) }}">{{ r.case.case_key }}</a><br>{{ r.case.title }}</td><td><span class="badge {% if r.label in ['High','Critical'] %}fail{% endif %}">{{ r.label }}</span></td><td>{{ r.score }}/16</td><td>{% if r.profile %}Impact {{ r.profile.business_impact }} · Complexity {{ r.profile.change_complexity }} · Regression {{ r.profile.regression_risk }} · Frequency {{ r.profile.user_frequency }}{% else %}Unassessed{% endif %}</td></tr>{% endfor %}</table></div></div></div></section>

<section class="panel" data-qpanel="impact"><div class="grid"><div class="card"><h2>AI-assisted impact / smart scope</h2><form class="form" method="post" action="{{ url_for('qa_impact') }}"><label>Change / acceptance criteria<textarea name="change_description" required>{{ inp.change_description if inp else '' }}</textarea></label><div class="inline"><label>Jira<input name="jira_key" value="{{ inp.jira_key if inp else '' }}"></label><label>Release<select name="release_id"><option value="">All cases</option>{% for r in releases %}<option value="{{ r.id }}" {% if inp and inp.release_id==r.id %}selected{% endif %}>{{ r.version }}</option>{% endfor %}</select></label><button class="prd-btn prd-btn-primary">Analyze</button></div></form>{% if analysis %}<div class="analysis"><b>{{ analysis.provider }}</b> · {{ analysis.summary }}{% if analysis.warning %}<br>{{ analysis.warning }}{% endif %}{% if analysis.risks %}<ul>{% for x in analysis.risks %}<li>{{ x }}</li>{% endfor %}</ul>{% endif %}</div><form class="form" method="post" action="{{ url_for('qa_smart_run') }}"><label>Run name<input name="name" required value="Impact run{% if inp and inp.jira_key %} — {{ inp.jira_key }}{% endif %}"></label><div class="inline"><label>Execution<select name="execution_type"><option>Automated</option><option>Manual</option></select></label><label>Environment<input name="environment"></label><label>Release<select name="release_id"><option value="">No release</option>{% for r in releases %}<option value="{{ r.id }}" {% if inp and inp.release_id==r.id %}selected{% endif %}>{{ r.version }}</option>{% endfor %}</select></label></div><div class="checks">{% for x in analysis_cases %}<label class="check"><input type="checkbox" name="case_ids" value="{{ x.row.case.id }}" {% if x.relevance!='Consider' %}checked{% endif %}><span><b>{{ x.relevance }} · {{ x.row.case.case_key }} — {{ x.row.case.title }}</b><br><span class="meta">{{ x.reason }}</span></span></label>{% endfor %}</div>{% if analysis_cases %}<button class="prd-btn prd-btn-primary">Create suggested run</button>{% endif %}</form>{% endif %}</div>
<div class="card"><h2>Failure clustering</h2>{% for x in clusters[:12] %}<div class="row"><div><div class="title">{{ x.category }} · {{ x.count }}</div><div class="meta">{{ x.case_keys|join(', ') }}<br>{{ x.signature }}</div></div></div>{% else %}<div class="help">No failures to cluster.</div>{% endfor %}<form method="post" action="{{ url_for('qa_failure_ai') }}"><button class="prd-btn">AI summarize failures</button></form>{% if failure_ai %}<div class="analysis"><b>{{ failure_ai.provider }}</b> · {{ failure_ai.summary }}<ul>{% for x in failure_ai.likely_common_causes %}<li>{{ x }}</li>{% endfor %}</ul><b>Next checks</b><ul>{% for x in failure_ai.next_checks %}<li>{{ x }}</li>{% endfor %}</ul></div>{% endif %}</div></div></section>

<section class="panel" data-qpanel="explore"><div class="grid"><div class="card"><h2>New exploratory session</h2><form class="form" method="post" action="{{ url_for('qa_exploratory') }}"><label>Title<input name="title" required></label><label>Charter<textarea name="charter" required></textarea></label><div class="inline"><label>Minutes<input type="number" min="0" name="duration_minutes" value="45"></label><label>Environment<input name="environment"></label></div><label>Jira keys<input name="jira_keys"></label><label>Coverage<textarea name="coverage"></textarea></label><label>Notes<textarea name="notes"></textarea></label><button class="prd-btn prd-btn-primary">Create session</button></form></div><div class="card"><h2>Sessions</h2>{% for s in sessions %}<div class="row"><div><div class="title">{{ s.title }}</div><div class="meta">{{ s.status }} · {{ s.duration_minutes }} min · {{ s.environment or 'No environment' }}{% if s.jira_keys %} · {{ s.jira_keys }}{% endif %}<br>{{ s.charter }}</div></div><form method="post" action="{{ url_for('qa_exploratory_status',session_id=s.id) }}"><select name="status" onchange="this.form.submit()">{% for v in exploratory_statuses %}<option {% if s.status==v %}selected{% endif %}>{{ v }}</option>{% endfor %}</select></form></div>{% else %}<div class="help">No sessions yet.</div>{% endfor %}</div></div></section>

<section class="panel" data-qpanel="auto"><div class="card"><h2>Automation health</h2><div class="help">Potentially flaky means recent history contains both passes and failures; it is a maintenance signal, not proof of a flaky test.</div><div class="scroll"><table class="table"><tr><th>Case</th><th>State</th><th>Attempts</th><th>Failure rate</th></tr>{% for r in automation %}<tr><td><a href="{{ url_for('test_case_details',case_key=r.case.case_key) }}">{{ r.case.case_key }}</a><br>{{ r.case.title }}</td><td><span class="badge {% if r.state=='Consistently failing' %}fail{% elif r.state=='Potentially flaky' %}block{% elif r.state=='Stable' %}pass{% endif %}">{{ r.state }}</span></td><td>{{ r.attempts }}</td><td>{{ r.flake_rate }}%</td></tr>{% endfor %}</table></div></div></section>
</main>{{ js|safe }}</body></html>"""
