services:
  - type: web
    name: python-playwright-qa-store
    runtime: python
    plan: free
    rootDir: qa_testing_playground
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn store:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true

  - type: web
    name: python-playwright-qa-playground
    runtime: python
    plan: free
    rootDir: qa_testing_playground
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn qa_playground:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true

  - type: web
    name: python-playwright-test-hub
    runtime: python
    plan: free
    region: frankfurt
    rootDir: test_hub
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JIRA_BASE_URL
        value: https://qa-test-store.atlassian.net/browse
      - key: DATABASE_URL
        fromDatabase:
          name: python-playwright-test-hub-db
          property: connectionString

databases:
  - name: python-playwright-test-hub-db
    plan: free
    region: frankfurt
    databaseName: test_hub
    user: test_hub
