import json
import os
from pathlib import Path
import re
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

import pytest
from pytest_bdd import given, when, then
from pageObjects.login import LoginPage
from pageObjects.ordersHistory import OrdersHistoryPage


FEATURES_DIR = Path(__file__).parent / "features"
TEST_HUB_CASE_IDS = {
    value.strip().upper()
    for value in os.getenv("TEST_CASE_IDS", "").split(",")
    if value.strip()
}
TEST_HUB_RUN_ID = os.getenv("TEST_RUN_ID", "").strip()
TEST_HUB_URL = os.getenv("TEST_HUB_URL", "").rstrip("/")
TEST_HUB_API_KEY = os.getenv("TEST_HUB_API_KEY", "").strip()
JENKINS_BUILD_NUMBER = os.getenv("BUILD_NUMBER", "").strip()
JENKINS_BUILD_URL = os.getenv("BUILD_URL", "").strip()

_case_id_by_nodeid = {}


def _normalize_case_token(value):
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def _known_bdd_case_ids():
    ids = set()
    pattern = re.compile(r"\b[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+\b")
    for feature_file in FEATURES_DIR.glob("*.feature"):
        ids.update(pattern.findall(feature_file.read_text(encoding="utf-8")))
    return sorted(ids, key=lambda value: len(_normalize_case_token(value)), reverse=True)


KNOWN_BDD_CASE_IDS = _known_bdd_case_ids()


# Read case_id from Scenario Outline example parameters generated by pytest
# so each expanded example keeps its stable Test Hub case ID.
def _case_id_from_callspec(node):
    callspec = getattr(node, "callspec", None)
    if not callspec:
        return None

    for value in callspec.params.values():
        if isinstance(value, dict):
            case_id = str(value.get("case_id", "")).strip().upper()
            if case_id:
                return case_id
    return None


# Resolve the Test Hub case ID for a collected pytest item before execution starts.
def _case_id_for_item(item):
    case_id = _case_id_from_callspec(item)
    if case_id:
        return case_id

    normalized_nodeid = _normalize_case_token(item.nodeid)
    for known_case_id in KNOWN_BDD_CASE_IDS:
        if _normalize_case_token(known_case_id) in normalized_nodeid:
            return known_case_id
    return None


def _hub_post(path, payload):
    if not TEST_HUB_RUN_ID:
        return

    request_data = Request(
        f"{TEST_HUB_URL}{path}",
        data=json.dumps(payload).encode("utf-8"),
        method="POST",
        headers={
            "Authorization": f"Bearer {TEST_HUB_API_KEY}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
    )
    try:
        with urlopen(request_data, timeout=15):
            pass
    except (HTTPError, URLError) as exc:
        print(f"[Test Hub] Failed to report to {path}: {exc}")


def pytest_configure(config):
    if TEST_HUB_RUN_ID and (not TEST_HUB_URL or not TEST_HUB_API_KEY):
        raise pytest.UsageError(
            "TEST_RUN_ID requires TEST_HUB_URL and TEST_HUB_API_KEY."
        )


# Filter the collected BDD tests so Jenkins executes only the case IDs
# selected in the current Test Hub test run.
def pytest_collection_modifyitems(config, items):
    if not TEST_HUB_CASE_IDS:
        return

    selected = []
    deselected = []

    # Separate requested Test Hub cases from all other collected BDD tests.
    for item in items:
        case_id = _case_id_for_item(item)
        if case_id in TEST_HUB_CASE_IDS:
            selected.append(item)
            _case_id_by_nodeid[item.nodeid] = case_id
        else:
            deselected.append(item)

    # Tell pytest/reporters which tests were removed from this execution.
    if deselected:
        config.hook.pytest_deselected(items=deselected)

    # Replace pytest's active collection with only the selected Test Hub cases.
    items[:] = selected

    # Print the selected case IDs in the Jenkins console for easier debugging.
    terminal = config.pluginmanager.get_plugin("terminalreporter")
    if terminal:
        selected_ids = ", ".join(sorted(TEST_HUB_CASE_IDS))
        terminal.write_line(
            f"[Test Hub] Selected {len(selected)} test(s): {selected_ids}"
        )


# Resolve the stable Test Hub case ID again when pytest-bdd starts the scenario.
def _scenario_case_id(request, scenario):
    case_id = _case_id_from_callspec(request.node)
    if case_id:
        return case_id

    name = getattr(scenario, "name", "") or ""
    match = re.match(r"^([A-Z0-9]+(?:-[A-Z0-9]+)+)\b", name.strip().upper())
    return match.group(1) if match else None


# Register the selected BDD scenario so its result can be reported back to Test Hub.
def pytest_bdd_before_scenario(request, feature, scenario):
    if not TEST_HUB_CASE_IDS:
        return

    case_id = _scenario_case_id(request, scenario)

    # Fail clearly if an unexpected case survives collection filtering.
    if case_id not in TEST_HUB_CASE_IDS:
        pytest.fail(
            f"Collected BDD case {case_id or '<unknown>'} was not selected by Test Hub."
        )

    _case_id_by_nodeid[request.node.nodeid] = case_id


def _report_result(report, result):
    case_id = _case_id_by_nodeid.get(report.nodeid)
    if not case_id or not TEST_HUB_RUN_ID:
        return

    error_message = ""
    if result == "Failed":
        error_message = getattr(report, "longreprtext", "") or ""

    _hub_post(
        f"/api/test-runs/{TEST_HUB_RUN_ID}/results",
        {
            "case_key": case_id,
            "result": result,
            "duration_ms": round(report.duration * 1000),
            "build_number": JENKINS_BUILD_NUMBER,
            "build_url": JENKINS_BUILD_URL,
            "error_message": error_message[-12000:],
        },
    )


def pytest_runtest_logreport(report):
    if report.when == "setup":
        if report.failed:
            _report_result(report, "Failed")
        elif report.skipped:
            _report_result(report, "Skipped")
        return

    if report.when == "call":
        if report.passed:
            _report_result(report, "Passed")
        elif report.failed:
            _report_result(report, "Failed")
        elif report.skipped:
            _report_result(report, "Skipped")
        return

    if report.when == "teardown" and report.failed:
        _report_result(report, "Failed")


def pytest_sessionfinish(session, exitstatus):
    if not TEST_HUB_RUN_ID or not TEST_HUB_URL or not TEST_HUB_API_KEY:
        return

    reported_ids = set(_case_id_by_nodeid.values())
    missing = TEST_HUB_CASE_IDS - reported_ids
    runner_status = "Completed" if exitstatus in (0, 1) and not missing else "Error"

    message = f"pytest finished with exit code {exitstatus}."
    if missing:
        message += " Selected case IDs were not reached: " + ", ".join(sorted(missing))

    _hub_post(
        f"/api/test-runs/{TEST_HUB_RUN_ID}/finish",
        {
            "status": runner_status,
            "message": message,
            "build_number": JENKINS_BUILD_NUMBER,
            "build_url": JENKINS_BUILD_URL,
        },
    )

@pytest.fixture
def shared_data(browserInstance, api_clients):
    data = {}
    yield data
    if data.get("order_id"):
        response = api_clients().deleteOrder(data["order_id"])
        assert response.status in (302, 404), "Failed to clean up the scenario's order"

@given("the user is on the login page")
def user_on_login_page(browserInstance, shared_data):
    login_page = LoginPage(browserInstance)
    login_page.navigate()
    login_page.verifyLoginPage()
    shared_data["login_page"] = login_page

@when("the admin logs in with valid credentials")
def admin_logs_in_with_credentials(admin_credentials, shared_data):
    shared_data["dashboard_page"] = shared_data["login_page"].login(
        admin_credentials["userEmail"], admin_credentials["userPassword"])

@then("the login page should be displayed")
def login_page_is_displayed(shared_data):
    shared_data["login_page"].verifyLoginPage()

@then("the Store page should be displayed")
def store_page_is_displayed(shared_data):
    shared_data["dashboard_page"].verifyStorePage()

@given("the admin is logged in")
def admin_is_logged_in(browserInstance, admin_credentials, shared_data):
    login_page = LoginPage(browserInstance)
    login_page.navigate()
    shared_data["dashboard_page"] = login_page.login(
        admin_credentials["userEmail"], admin_credentials["userPassword"]
    )

@given("the admin has added a product to the cart")
def admin_has_added_product(admin_credentials, browserInstance, e2e_checkout_data, shared_data):
    login_page = LoginPage(browserInstance)
    login_page.navigate()

    dashboard_page = login_page.login(
        admin_credentials["userEmail"], admin_credentials["userPassword"]
    )

    product = dashboard_page.addProductToCart(e2e_checkout_data["productId"])

    shared_data["dashboard_page"] = dashboard_page
    shared_data["product"] = product


@given("the admin has added multiple products to the cart")
def admin_has_added_multiple_products(admin_credentials, browserInstance, shared_data):
    login_page = LoginPage(browserInstance)
    login_page.navigate()

    dashboard_page = login_page.login(
        admin_credentials["userEmail"], admin_credentials["userPassword"]
    )

    first_product = dashboard_page.addProductToCart(1)
    second_product = dashboard_page.addProductToCart(2)

    shared_data["dashboard_page"] = dashboard_page
    shared_data["products"] = [first_product, second_product]

@when("the admin adds a product to the cart")
def admin_adds_product(e2e_checkout_data, shared_data):

    shared_data["product"] = shared_data["dashboard_page"].addProductToCart(e2e_checkout_data["productId"])

@when("the admin opens the cart")
def admin_opens_cart(shared_data):
    shared_data["cart_page"] = shared_data["dashboard_page"].openCart()


@when("the admin proceeds to checkout")
def admin_proceeds_to_checkout(shared_data):
    shared_data["total"] = shared_data["cart_page"].getTotal()
    shared_data["checkout_page"] = shared_data["cart_page"].proceedToCheckout()


@then("the checkout page should be displayed")
def checkout_page_is_displayed(shared_data):
    shared_data["checkout_page"].verifyCheckoutPage()


@when("the admin enters valid checkout information")
def admin_enters_checkout_information(e2e_checkout_data, shared_data):
    shared_data["checkout_page"].enterCheckoutInformation(
        e2e_checkout_data["customer"], e2e_checkout_data["payment"]
    )


@when("the admin places the order")
def admin_places_order(shared_data):
    shared_data["confirmation_page"] = shared_data["checkout_page"].placeOrder()


@then("the order should be created successfully")
def order_created_successfully(shared_data):
    shared_data["confirmation_page"].verifyOrderSuccess()


@then("an order number should be displayed")
def order_number_displayed(shared_data):
    shared_data["order_id"] = shared_data["confirmation_page"].getOrderNumber()


@when("the admin navigates to order history")
def navigate_to_order_history(shared_data):
    shared_data["orders_page"] = shared_data["confirmation_page"].openOrderHistory()


@then("the created order should appear in the order history")
def created_order_appears(shared_data):
    shared_data["orders_page"].verifyOrderExists(shared_data["order_id"])


@when("the admin opens the created order")
@when("the viewer opens the created order")
def open_created_order(shared_data):
    shared_data["details_page"] = shared_data["orders_page"].selectOrder(
        shared_data["order_id"]
    )


@then("the correct order number should be displayed")
def verify_order_number(shared_data):
    shared_data["details_page"].verifyOrderNumber()


@given("an order exists for permission checks")
def order_exists_for_permissions(seeded_order, shared_data):
    shared_data["order_id"] = seeded_order["id"]
    shared_data["seeded_order"] = seeded_order


@given("the orders viewer is logged in")
def viewer_is_logged_in(browserInstance, viewer_credentials, shared_data):
    login = LoginPage(browserInstance)
    login.navigate()
    shared_data["login_page"] = login
    shared_data["orders_page"] = login.loginAsViewer(viewer_credentials)


@when("the admin deletes the order from Order Details and confirms")
def admin_deletes_order_from_details(shared_data):
    shared_data["details_page"].deleteOrder()


@then("the deleted order should not appear in Order History")
def deleted_order_is_absent(shared_data):
    shared_data["orders_page"].verifyOrderRemoved(shared_data["order_id"])


@when("the user logs out from Order History")
def user_logs_out_from_order_history(browserInstance, shared_data):
    OrdersHistoryPage(browserInstance).logout()
    shared_data["login_page"] = LoginPage(browserInstance)


@when("the second admin logs in")
def second_admin_logs_in(second_admin_credentials, shared_data):
    shared_data["dashboard_page"] = shared_data["login_page"].login(
        second_admin_credentials["userEmail"], second_admin_credentials["userPassword"]
    )


@when("the admin opens Order History from the Store")
def admin_opens_history_from_store(shared_data):
    shared_data["orders_page"] = shared_data["dashboard_page"].selectOrdersNaviLink()
