import re
from playwright.sync_api import Playwright, sync_playwright, expect
from utils.config import playgroundURL


def test_run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context()
    page = context.new_page()
    page.goto(playgroundURL)
    page.get_by_test_id("username-input").fill("tester")
    page.get_by_test_id("password-input").fill("password123")
    page.get_by_test_id("terms-checkbox").check()
    page.get_by_test_id("login-button").click()
    with page.expect_popup() as page1_info:
        page.get_by_test_id("popup-link").click()
    page1 = page1_info.value
    page1.get_by_test_id("popup-button").click()
    page1.close()
    page.get_by_test_id("full-name").fill("giovvani")
    page.get_by_role("textbox", name="Email input").fill("gio@gmail.com")
    page.get_by_role("spinbutton", name="Number input").click()
    page.get_by_role("spinbutton", name="Number input").click()
    page.get_by_role("spinbutton", name="Number input").dblclick()
    page.get_by_role("spinbutton", name="Number input").dblclick()
    page.get_by_role("textbox", name="Date input").fill("2017-05-09")
    page.get_by_label("Select dropdown").select_option("at")
    page.get_by_role("textbox", name="Textarea").fill("new text")
    page.get_by_test_id("checkbox-python").check()
    page.get_by_role("slider", name="Range slider:").fill("7")
    page.get_by_test_id("submit-profile").click()
    page.get_by_role("button", name="Details").click()
    page.get_by_role("button", name="Settings").click()
    page.get_by_role("button", name="Open Accordion").click()
    page.get_by_role("button", name="Close Accordion").click()
    page.get_by_role("button", name="Open Modal").click()
    page.get_by_role("textbox", name="Modal input").fill("dsaas")
    page.get_by_role("button", name="Close Modal").click()
    page.get_by_role("button", name="Show Toast").click()
    page.get_by_role("button", name="Add Dynamic Element").click()
    page.get_by_test_id("dynamic-button").click()
    page.get_by_role("button", name="Remove Dynamic Element").click()
    page.get_by_role("button", name="Load Data (2 seconds)").click()
    page.get_by_text("✅ Data loaded successfully").click()
    page.get_by_role("button", name="Hover or Focus Me").click()
    page.get_by_role("tooltip", name="This is a tooltip").click()
    page.get_by_role("button", name="Right-click Me").click(button="right")
    page.get_by_role("button", name="Context Action").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.locator("[data-testid=\"dialog-frame\"]").content_frame.get_by_role("button", name="JavaScript Alert").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.locator("[data-testid=\"dialog-frame\"]").content_frame.get_by_role("button", name="Confirm Dialog").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.locator("[data-testid=\"dialog-frame\"]").content_frame.get_by_role("button", name="Prompt Dialog").click()
    page.get_by_role("link", name="Internal Page").click()
    page.get_by_test_id("back-link").click()
    with page.expect_popup() as page2_info:
        page.get_by_test_id("popup-link-secondary").click()
    page2 = page2_info.value
    page2.get_by_test_id("popup-button").click()
    page2.close()
    with page.expect_popup() as page3_info:
        page.get_by_role("link", name="Open New Tab").click()
    page3 = page3_info.value
    page3.close()
    page.get_by_role("link", name="Anchor Link").click()
    page.get_by_role("button", name="Back to Top").click()
    page.get_by_role("cell", name="Product Owner").click()
    page.get_by_role("cell", name="Inactive").click()
    page.locator("#dragList").get_by_text("Test Case A").click()
    page.locator("#dragList").get_by_text("Test Case B").click()
    page.locator("#dragList").get_by_text("Test Case C").click()
    page.get_by_role("button", name="Move Selected Item").click()
    page.get_by_role("textbox", name="Type here, then press Enter").click()
    page.get_by_role("textbox", name="Type here, then press Enter").fill("asdasd")
    page.get_by_role("textbox", name="Type here, then press Enter").press("Enter")
    page.get_by_text("Scroll checkpoint 4").click()
    page.get_by_role("button", name="Back to Top").click()
    page.get_by_test_id("logout-button").click()

    # ---------------------
    context.close()
    browser.close()
